<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net45</TargetFrameworks>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageId>AutoPipe</PackageId>
    <Authors>Serhii Solomentsev</Authors>
    <Company>Soft Consulting US</Company>
    <Description>AutoPipe streamlines your workflow by letting you focus on business logic while it manages pipeline execution, parameter handling, and method orchestration. Build robust, flexible, and easily refactorable pipelines with minimal effort.</Description>
    <Copyright>Soft Consulting US © 2025</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/wittylion/AutoPipe/wiki</PackageProjectUrl>
    <RepositoryUrl>https://github.com/wittylion/AutoPipe</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReleaseNotes>

      Effortlessly build and refactor pipelines with AutoPipe:
      - Create processors by inheriting from AutoProcessor.
      - Annotate methods with [Run] to execute them in the pipeline; rename methods freely without refactoring dependencies.
      - Add new parameters by returning them from methods prefixed with Get, or return anonymous objects for multiple values.
      - Use attributes to control pipeline behavior:
        [Run] - Mark a method to be executed in the pipeline.
        [RunAll] - Execute all methods in the processor.
        [Skip] - Exclude a method from execution.
        [Aka("Custom Name")] - Alias methods and processors for flexible referencing.
        [Is("Description")] - Add descriptions for better debugging and documentation.
        [Order(15)] - Specify execution order for processors and methods.
        [After("Previous")] - Define execution dependencies between processors.
        [Or("Default value")] - Provide fallback values for missing properties.
        [Required(Message = "Cannot proceed without this parameter", Halt = true)] - Enforce required parameters and control pipeline flow.
        [Strict] - Require all parameters for a method.

      For more details, visit the documentation: https://github.com/wittylion/AutoPipe/wiki

    </PackageReleaseNotes>
    <NeutralLanguage>English</NeutralLanguage>
    <PackageTags>Easy Refactoring Pipelines SOLID Processors Chain</PackageTags>
    <Version>2.2.0</Version>
    <AssemblyVersion>2.2.0.0</AssemblyVersion>
    <PackageIcon>pipelines-icon.png</PackageIcon>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
    <None Include="pipelines-icon.png" Pack="true" Visible="false" PackagePath="" />
  </ItemGroup>
</Project>
